// Seed question bank — 105 items ported from the approved prototype.
// 7 categories x 3 difficulty levels x 5 items.
// Picture items reference SVG files served by the API at /static/images/<name>.svg
// (later these can be re-uploaded to Cloudinary from the admin panel).

export interface SeedQuestion {
  categorySlug: string;
  type: 'MULTIPLE_CHOICE' | 'PICTURE' | 'WORD_PUZZLE';
  difficulty: 'EASY' | 'AVERAGE' | 'DIFFICULT';
  questionText: string;
  codeSnippet: string | null;
  imageUrl: string | null;
  answer: string;
  alternates: string[];
  choices: string[];
  hint: string | null;
  explanation: string;
  topic: string;
}

export const questions: SeedQuestion[] = [
  {
    categorySlug: "prog",
    type: "MULTIPLE_CHOICE",
    difficulty: "EASY",
    questionText: "A named storage location in memory whose value can change while the program runs.",
    codeSnippet: null,
    imageUrl: null,
    answer: "Variable",
    alternates: [],
    choices: ["Constant","Function","Keyword"],
    hint: "You declare it with a data type, like int age;",
    explanation: "A variable holds a value that can be changed during execution. A constant cannot be changed once set.",
    topic: "Variables",
  },
  {
    categorySlug: "prog",
    type: "WORD_PUZZLE",
    difficulty: "EASY",
    questionText: "A finite set of step-by-step instructions for solving a problem.",
    codeSnippet: null,
    imageUrl: null,
    answer: "ALGORITHM",
    alternates: [],
    choices: [],
    hint: "A cooking recipe is an everyday example.",
    explanation: "An algorithm is an ordered, finite list of steps. Programs are algorithms written in a programming language.",
    topic: "Problem Solving",
  },
  {
    categorySlug: "prog",
    type: "PICTURE",
    difficulty: "EASY",
    questionText: "Name this flowchart symbol.",
    codeSnippet: null,
    imageUrl: "/static/images/flow_decision.svg",
    answer: "Decision",
    alternates: ["decision symbol","diamond"],
    choices: [],
    hint: "It asks a yes-or-no question.",
    explanation: "The diamond is the decision symbol. It branches the flow based on a condition (Yes/No).",
    topic: "Flowcharting",
  },
  {
    categorySlug: "prog",
    type: "MULTIPLE_CHOICE",
    difficulty: "EASY",
    questionText: "Which data type stores only true or false values?",
    codeSnippet: null,
    imageUrl: null,
    answer: "Boolean",
    alternates: [],
    choices: ["Integer","Char","Float"],
    hint: "Named after mathematician George Boole.",
    explanation: "A Boolean has only two possible values: true or false. It is used for conditions.",
    topic: "Data Types",
  },
  {
    categorySlug: "prog",
    type: "WORD_PUZZLE",
    difficulty: "EASY",
    questionText: "Forgetting a semicolon at the end of a statement causes a ___ error.",
    codeSnippet: null,
    imageUrl: null,
    answer: "SYNTAX",
    alternates: [],
    choices: [],
    hint: "It is about the grammar rules of the language.",
    explanation: "A syntax error breaks the grammar rules of the language and is caught by the compiler before the program runs.",
    topic: "Errors",
  },
  {
    categorySlug: "prog",
    type: "MULTIPLE_CHOICE",
    difficulty: "AVERAGE",
    questionText: "What is the value of x after this statement runs (Java or C)?",
    codeSnippet: "int x = 7 / 2;",
    imageUrl: null,
    answer: "3",
    alternates: [],
    choices: ["3.5","4","2"],
    hint: "Both operands are integers.",
    explanation: "Dividing two integers performs integer division, so the decimal part is dropped: 7 / 2 = 3.",
    topic: "Operators",
  },
  {
    categorySlug: "prog",
    type: "PICTURE",
    difficulty: "AVERAGE",
    questionText: "What is the exact output of this code?",
    codeSnippet: null,
    imageUrl: "/static/images/code_loop.svg",
    answer: "012",
    alternates: ["0 1 2","0,1,2"],
    choices: [],
    hint: "The loop stops before i reaches 3.",
    explanation: "i starts at 0 and the loop runs while i < 3, printing 0, 1, and 2.",
    topic: "Loops",
  },
  {
    categorySlug: "prog",
    type: "MULTIPLE_CHOICE",
    difficulty: "AVERAGE",
    questionText: "A function that calls itself to solve smaller versions of a problem uses ___.",
    codeSnippet: null,
    imageUrl: null,
    answer: "Recursion",
    alternates: [],
    choices: ["Iteration","Overloading","Encapsulation"],
    hint: "It needs a base case to stop.",
    explanation: "Recursion is when a function calls itself. It must have a base case, or it will never stop.",
    topic: "Functions",
  },
  {
    categorySlug: "prog",
    type: "WORD_PUZZLE",
    difficulty: "AVERAGE",
    questionText: "OOP concept where a class acquires the properties and methods of another class.",
    codeSnippet: null,
    imageUrl: null,
    answer: "INHERITANCE",
    alternates: [],
    choices: [],
    hint: "Children get traits from their parents.",
    explanation: "Inheritance lets a subclass reuse and extend the members of a superclass (e.g., Student extends User).",
    topic: "OOP",
  },
  {
    categorySlug: "prog",
    type: "PICTURE",
    difficulty: "AVERAGE",
    questionText: "Name this flowchart symbol.",
    codeSnippet: null,
    imageUrl: "/static/images/flow_io.svg",
    answer: "Input/Output",
    alternates: ["input output","io","i/o","data","parallelogram"],
    choices: [],
    hint: "Used for \"Read\" or \"Display\" steps.",
    explanation: "The parallelogram represents input or output, such as reading a value or displaying a result.",
    topic: "Flowcharting",
  },
  {
    categorySlug: "prog",
    type: "MULTIPLE_CHOICE",
    difficulty: "DIFFICULT",
    questionText: "In Java, what does this code print?",
    codeSnippet: "int a = 5;\nint b = a++ + ++a;\nSystem.out.println(b);",
    imageUrl: null,
    answer: "12",
    alternates: [],
    choices: ["11","10","13"],
    hint: null,
    explanation: "a++ gives 5 (then a becomes 6). ++a makes a 7 and gives 7. So b = 5 + 7 = 12.",
    topic: "Operators",
  },
  {
    categorySlug: "prog",
    type: "MULTIPLE_CHOICE",
    difficulty: "DIFFICULT",
    questionText: "Dog and Cat both override speak(). Calling speak() through an Animal reference runs the correct version. Which principle is this?",
    codeSnippet: null,
    imageUrl: null,
    answer: "Polymorphism",
    alternates: [],
    choices: ["Encapsulation","Abstraction","Inheritance"],
    hint: null,
    explanation: "Polymorphism lets one interface (Animal.speak) behave differently depending on the actual object type at runtime.",
    topic: "OOP",
  },
  {
    categorySlug: "prog",
    type: "WORD_PUZZLE",
    difficulty: "DIFFICULT",
    questionText: "The program runs without crashing but computes the average wrong. This is a ___ error.",
    codeSnippet: null,
    imageUrl: null,
    answer: "LOGIC",
    alternates: [],
    choices: [],
    hint: null,
    explanation: "A logic error does not stop the program. It produces wrong results because the algorithm itself is wrong.",
    topic: "Errors",
  },
  {
    categorySlug: "prog",
    type: "PICTURE",
    difficulty: "DIFFICULT",
    questionText: "What value is printed?",
    codeSnippet: null,
    imageUrl: "/static/images/code_while.svg",
    answer: "3",
    alternates: ["three"],
    choices: [],
    hint: null,
    explanation: "n goes 10 → 5 → 2 → 1. The loop body runs 3 times before n > 1 is false, so c = 3.",
    topic: "Loops",
  },
  {
    categorySlug: "prog",
    type: "MULTIPLE_CHOICE",
    difficulty: "DIFFICULT",
    questionText: "In Java, when an object is passed to a method, what is actually copied?",
    codeSnippet: null,
    imageUrl: null,
    answer: "The value of the reference",
    alternates: [],
    choices: ["The entire object","Nothing is copied","A deep clone of the object"],
    hint: null,
    explanation: "Java is pass-by-value. For objects, the value copied is the reference, so the method can change the object but cannot reassign the caller's variable.",
    topic: "Functions",
  },
  {
    categorySlug: "dsa",
    type: "PICTURE",
    difficulty: "EASY",
    questionText: "Name this data structure.",
    codeSnippet: null,
    imageUrl: "/static/images/stack.svg",
    answer: "Stack",
    alternates: [],
    choices: [],
    hint: "Think of a pile of plates.",
    explanation: "A stack is Last-In, First-Out (LIFO). Items are pushed onto and popped from the top only.",
    topic: "Stacks",
  },
  {
    categorySlug: "dsa",
    type: "PICTURE",
    difficulty: "EASY",
    questionText: "Name this data structure.",
    codeSnippet: null,
    imageUrl: "/static/images/queue.svg",
    answer: "Queue",
    alternates: [],
    choices: [],
    hint: "Like the line at the canteen.",
    explanation: "A queue is First-In, First-Out (FIFO). Items enter at the rear and leave from the front.",
    topic: "Queues",
  },
  {
    categorySlug: "dsa",
    type: "MULTIPLE_CHOICE",
    difficulty: "EASY",
    questionText: "Accessing an array element by its index takes what time complexity?",
    codeSnippet: null,
    imageUrl: null,
    answer: "O(1)",
    alternates: [],
    choices: ["O(n)","O(log n)","O(n²)"],
    hint: "The address is computed directly.",
    explanation: "Array access by index is constant time, O(1), because the element's address is computed directly.",
    topic: "Complexity",
  },
  {
    categorySlug: "dsa",
    type: "WORD_PUZZLE",
    difficulty: "EASY",
    questionText: "The topmost node of a tree, the only node with no parent.",
    codeSnippet: null,
    imageUrl: null,
    answer: "ROOT",
    alternates: [],
    choices: [],
    hint: "Plants have them underground.",
    explanation: "The root is the starting node of a tree. Every other node descends from it.",
    topic: "Trees",
  },
  {
    categorySlug: "dsa",
    type: "MULTIPLE_CHOICE",
    difficulty: "EASY",
    questionText: "Which search algorithm requires the list to be sorted first?",
    codeSnippet: null,
    imageUrl: null,
    answer: "Binary search",
    alternates: [],
    choices: ["Linear search","Sequential search","Random search"],
    hint: "It keeps cutting the list in half.",
    explanation: "Binary search compares with the middle element and discards half each step, which only works on sorted data.",
    topic: "Searching",
  },
  {
    categorySlug: "dsa",
    type: "PICTURE",
    difficulty: "AVERAGE",
    questionText: "Type the IN-ORDER traversal of this binary tree (numbers only).",
    codeSnippet: null,
    imageUrl: "/static/images/bintree.svg",
    answer: "1234567",
    alternates: ["1 2 3 4 5 6 7","1,2,3,4,5,6,7"],
    choices: [],
    hint: "Left, Root, Right.",
    explanation: "In-order visits Left → Root → Right. On a binary search tree this always gives sorted order: 1 2 3 4 5 6 7.",
    topic: "Trees",
  },
  {
    categorySlug: "dsa",
    type: "PICTURE",
    difficulty: "AVERAGE",
    questionText: "Name this data structure.",
    codeSnippet: null,
    imageUrl: "/static/images/linkedlist.svg",
    answer: "Linked list",
    alternates: ["singly linked list","linkedlist"],
    choices: [],
    hint: "Each node points to the next.",
    explanation: "A linked list stores nodes containing data and a pointer to the next node. The last node points to NULL.",
    topic: "Linked Lists",
  },
  {
    categorySlug: "dsa",
    type: "MULTIPLE_CHOICE",
    difficulty: "AVERAGE",
    questionText: "Push 1, push 2, push 3, pop, push 4. Which value is now on top of the stack?",
    codeSnippet: null,
    imageUrl: null,
    answer: "4",
    alternates: [],
    choices: ["3","2","1"],
    hint: "Pop removes the most recent item.",
    explanation: "After pushing 1, 2, 3 and popping (removes 3), pushing 4 places it on top: [1, 2, 4].",
    topic: "Stacks",
  },
  {
    categorySlug: "dsa",
    type: "WORD_PUZZLE",
    difficulty: "AVERAGE",
    questionText: "Sorting algorithm that repeatedly swaps adjacent elements that are in the wrong order.",
    codeSnippet: null,
    imageUrl: null,
    answer: "BUBBLE SORT",
    alternates: [],
    choices: [],
    hint: "Large values \"float\" to the end.",
    explanation: "Bubble sort compares neighbors and swaps them. It is simple but O(n²).",
    topic: "Sorting",
  },
  {
    categorySlug: "dsa",
    type: "MULTIPLE_CHOICE",
    difficulty: "AVERAGE",
    questionText: "What is the worst-case time complexity of binary search?",
    codeSnippet: null,
    imageUrl: null,
    answer: "O(log n)",
    alternates: [],
    choices: ["O(n)","O(1)","O(n log n)"],
    hint: "The search space halves each step.",
    explanation: "Halving n each step takes about log₂ n steps, so binary search is O(log n).",
    topic: "Complexity",
  },
  {
    categorySlug: "dsa",
    type: "MULTIPLE_CHOICE",
    difficulty: "DIFFICULT",
    questionText: "Which algorithm sorts in place, averages O(n log n), but degrades to O(n²) with bad pivots?",
    codeSnippet: null,
    imageUrl: null,
    answer: "Quick sort",
    alternates: [],
    choices: ["Merge sort","Heap sort","Insertion sort"],
    hint: null,
    explanation: "Quick sort partitions around a pivot. Poor pivot choices (e.g., already sorted data) cause O(n²).",
    topic: "Sorting",
  },
  {
    categorySlug: "dsa",
    type: "MULTIPLE_CHOICE",
    difficulty: "DIFFICULT",
    questionText: "Enqueue A, B, C. Dequeue. Enqueue D. Dequeue. Which element is now at the front?",
    codeSnippet: null,
    imageUrl: null,
    answer: "C",
    alternates: [],
    choices: ["B","D","A"],
    hint: null,
    explanation: "A B C → dequeue A → B C → enqueue D → B C D → dequeue B → C D. The front is C.",
    topic: "Queues",
  },
  {
    categorySlug: "dsa",
    type: "WORD_PUZZLE",
    difficulty: "DIFFICULT",
    questionText: "Graph traversal that visits nodes level by level using a queue (acronym).",
    codeSnippet: null,
    imageUrl: null,
    answer: "BFS",
    alternates: ["breadth first search"],
    choices: [],
    hint: null,
    explanation: "Breadth-First Search explores all neighbors first, using a queue. DFS uses a stack or recursion.",
    topic: "Graphs",
  },
  {
    categorySlug: "dsa",
    type: "PICTURE",
    difficulty: "DIFFICULT",
    questionText: "Type the PRE-ORDER traversal of this binary tree (numbers only).",
    codeSnippet: null,
    imageUrl: "/static/images/bintree.svg",
    answer: "4213657",
    alternates: ["4 2 1 3 6 5 7","4,2,1,3,6,5,7"],
    choices: [],
    hint: null,
    explanation: "Pre-order visits Root → Left → Right: 4, then 2 1 3, then 6 5 7.",
    topic: "Trees",
  },
  {
    categorySlug: "dsa",
    type: "MULTIPLE_CHOICE",
    difficulty: "DIFFICULT",
    questionText: "Which structure gives average O(1) lookup, insert, and delete by key?",
    codeSnippet: null,
    imageUrl: null,
    answer: "Hash table",
    alternates: [],
    choices: ["Binary search tree","Linked list","Sorted array"],
    hint: null,
    explanation: "A hash table computes the storage index from the key, giving average constant time operations.",
    topic: "Hashing",
  },
  {
    categorySlug: "dbms",
    type: "MULTIPLE_CHOICE",
    difficulty: "EASY",
    questionText: "Which SQL command retrieves data from a table?",
    codeSnippet: null,
    imageUrl: null,
    answer: "SELECT",
    alternates: [],
    choices: ["INSERT","UPDATE","DROP"],
    hint: "You \"choose\" the columns you want.",
    explanation: "SELECT reads rows. INSERT adds, UPDATE changes, and DROP deletes a whole table.",
    topic: "SQL",
  },
  {
    categorySlug: "dbms",
    type: "PICTURE",
    difficulty: "EASY",
    questionText: "The key icon marks which kind of key?",
    codeSnippet: null,
    imageUrl: "/static/images/pk_table.svg",
    answer: "Primary key",
    alternates: ["pk","primary"],
    choices: [],
    hint: "It uniquely identifies each row.",
    explanation: "A primary key uniquely identifies every row and cannot be NULL.",
    topic: "Keys",
  },
  {
    categorySlug: "dbms",
    type: "WORD_PUZZLE",
    difficulty: "EASY",
    questionText: "In the relational model, a row of a table is formally called a ___.",
    codeSnippet: null,
    imageUrl: null,
    answer: "TUPLE",
    alternates: ["record","row"],
    choices: [],
    hint: "Rhymes with \"couple\".",
    explanation: "Relation = table, tuple = row, attribute = column.",
    topic: "Relational Model",
  },
  {
    categorySlug: "dbms",
    type: "MULTIPLE_CHOICE",
    difficulty: "EASY",
    questionText: "What does DBMS stand for?",
    codeSnippet: null,
    imageUrl: null,
    answer: "Database Management System",
    alternates: [],
    choices: ["Data Backup Management Software","Digital Base Mapping System","Database Monitoring Service"],
    hint: "It manages databases.",
    explanation: "A Database Management System is software for creating, accessing, and managing databases (e.g., PostgreSQL).",
    topic: "Fundamentals",
  },
  {
    categorySlug: "dbms",
    type: "WORD_PUZZLE",
    difficulty: "EASY",
    questionText: "The overall structure or \"blueprint\" of a database: its tables, columns, and relationships.",
    codeSnippet: null,
    imageUrl: null,
    answer: "SCHEMA",
    alternates: [],
    choices: [],
    hint: "Prisma keeps it in a file of this name.",
    explanation: "A schema defines how data is organized. In this system it is written in Prisma's schema.prisma file.",
    topic: "Fundamentals",
  },
  {
    categorySlug: "dbms",
    type: "PICTURE",
    difficulty: "AVERAGE",
    questionText: "What cardinality does this ERD relationship show?",
    codeSnippet: null,
    imageUrl: "/static/images/crowsfoot.svg",
    answer: "One to many",
    alternates: ["1:m","1 to many","one-to-many","1:n","1 to n"],
    choices: [],
    hint: "Look at the \"crow's foot\" end.",
    explanation: "One bar means \"one\"; the crow's foot means \"many\". One customer can place many orders.",
    topic: "ERD",
  },
  {
    categorySlug: "dbms",
    type: "MULTIPLE_CHOICE",
    difficulty: "AVERAGE",
    questionText: "What does this query return?",
    codeSnippet: "SELECT COUNT(*) FROM students\nWHERE year_level = 3;",
    imageUrl: null,
    answer: "The number of 3rd-year students",
    alternates: [],
    choices: ["The names of 3rd-year students","All students","An error"],
    hint: "COUNT returns a number.",
    explanation: "COUNT(*) returns how many rows match the WHERE condition, a single number.",
    topic: "SQL",
  },
  {
    categorySlug: "dbms",
    type: "MULTIPLE_CHOICE",
    difficulty: "AVERAGE",
    questionText: "A column in one table that refers to the primary key of another table.",
    codeSnippet: null,
    imageUrl: null,
    answer: "Foreign key",
    alternates: [],
    choices: ["Candidate key","Super key","Composite key"],
    hint: "It \"comes from\" another table.",
    explanation: "A foreign key enforces referential integrity; e.g., questions.category_id references categories.",
    topic: "Keys",
  },
  {
    categorySlug: "dbms",
    type: "WORD_PUZZLE",
    difficulty: "AVERAGE",
    questionText: "SQL clause used to filter GROUPS after GROUP BY.",
    codeSnippet: null,
    imageUrl: null,
    answer: "HAVING",
    alternates: [],
    choices: [],
    hint: "WHERE filters rows; this filters groups.",
    explanation: "HAVING applies conditions to aggregated groups, e.g., HAVING COUNT(*) > 1.",
    topic: "SQL",
  },
  {
    categorySlug: "dbms",
    type: "PICTURE",
    difficulty: "AVERAGE",
    questionText: "What number does this query return?",
    codeSnippet: null,
    imageUrl: "/static/images/sql_query.svg",
    answer: "3",
    alternates: ["three"],
    choices: [],
    hint: "DISTINCT removes duplicates.",
    explanation: "The distinct departments are IT, HR, and Sales, so COUNT(DISTINCT dept) = 3.",
    topic: "SQL",
  },
  {
    categorySlug: "dbms",
    type: "MULTIPLE_CHOICE",
    difficulty: "DIFFICULT",
    questionText: "A non-key column depends on another non-key column (transitive dependency). Which normal form is violated?",
    codeSnippet: null,
    imageUrl: null,
    answer: "3NF",
    alternates: [],
    choices: ["1NF","2NF","4NF"],
    hint: null,
    explanation: "Third Normal Form requires no transitive dependencies: non-key columns must depend only on the key.",
    topic: "Normalization",
  },
  {
    categorySlug: "dbms",
    type: "MULTIPLE_CHOICE",
    difficulty: "DIFFICULT",
    questionText: "Which JOIN returns ALL rows from the left table, even when there is no match on the right?",
    codeSnippet: null,
    imageUrl: null,
    answer: "LEFT JOIN",
    alternates: [],
    choices: ["INNER JOIN","CROSS JOIN","RIGHT JOIN"],
    hint: null,
    explanation: "LEFT JOIN keeps every left row and fills unmatched right columns with NULL.",
    topic: "SQL",
  },
  {
    categorySlug: "dbms",
    type: "WORD_PUZZLE",
    difficulty: "DIFFICULT",
    questionText: "ACID property meaning a transaction happens completely or not at all.",
    codeSnippet: null,
    imageUrl: null,
    answer: "ATOMICITY",
    alternates: [],
    choices: [],
    hint: null,
    explanation: "Atomicity treats a transaction as one indivisible unit. If any step fails, everything is rolled back.",
    topic: "Transactions",
  },
  {
    categorySlug: "dbms",
    type: "MULTIPLE_CHOICE",
    difficulty: "DIFFICULT",
    questionText: "Two transactions update the same row at the same time and one change silently overwrites the other. This is a ___.",
    codeSnippet: null,
    imageUrl: null,
    answer: "Lost update",
    alternates: [],
    choices: ["Dirty read","Phantom read","Deadlock"],
    hint: null,
    explanation: "A lost update happens when concurrent writes overwrite each other without isolation or locking.",
    topic: "Transactions",
  },
  {
    categorySlug: "dbms",
    type: "MULTIPLE_CHOICE",
    difficulty: "DIFFICULT",
    questionText: "A table has a repeating group: phone1, phone2, phone3 columns. Which normal form does it fail first?",
    codeSnippet: null,
    imageUrl: null,
    answer: "1NF",
    alternates: [],
    choices: ["2NF","3NF","BCNF"],
    hint: null,
    explanation: "First Normal Form requires atomic values and no repeating groups. Phones should go in a separate table.",
    topic: "Normalization",
  },
  {
    categorySlug: "net",
    type: "PICTURE",
    difficulty: "EASY",
    questionText: "Name this network topology.",
    codeSnippet: null,
    imageUrl: "/static/images/star.svg",
    answer: "Star topology",
    alternates: ["star"],
    choices: [],
    hint: "All devices connect to one central device.",
    explanation: "In a star topology every node connects to a central switch or hub. If one cable fails, only that node is affected.",
    topic: "Topologies",
  },
  {
    categorySlug: "net",
    type: "PICTURE",
    difficulty: "EASY",
    questionText: "Name this network topology.",
    codeSnippet: null,
    imageUrl: "/static/images/bus.svg",
    answer: "Bus topology",
    alternates: ["bus"],
    choices: [],
    hint: "One backbone cable with terminators.",
    explanation: "A bus topology shares one backbone cable. A break in the backbone brings the whole network down.",
    topic: "Topologies",
  },
  {
    categorySlug: "net",
    type: "MULTIPLE_CHOICE",
    difficulty: "EASY",
    questionText: "Which device forwards packets between DIFFERENT networks?",
    codeSnippet: null,
    imageUrl: null,
    answer: "Router",
    alternates: [],
    choices: ["Switch","Hub","Repeater"],
    hint: "Your home Wi-Fi box has one to reach the internet.",
    explanation: "A router works at the Network layer and uses IP addresses to route packets between networks.",
    topic: "Devices",
  },
  {
    categorySlug: "net",
    type: "WORD_PUZZLE",
    difficulty: "EASY",
    questionText: "A unique numerical label assigned to each device on a network, e.g., 192.168.1.10.",
    codeSnippet: null,
    imageUrl: null,
    answer: "IP ADDRESS",
    alternates: [],
    choices: [],
    hint: "Starts with the letters of Internet Protocol.",
    explanation: "An IP address identifies a host on a network so that packets can be delivered to it.",
    topic: "Addressing",
  },
  {
    categorySlug: "net",
    type: "MULTIPLE_CHOICE",
    difficulty: "EASY",
    questionText: "How many layers does the OSI model have?",
    codeSnippet: null,
    imageUrl: null,
    answer: "7",
    alternates: [],
    choices: ["5","4","6"],
    hint: "\"Please Do Not Throw Sausage Pizza Away\".",
    explanation: "Physical, Data Link, Network, Transport, Session, Presentation, Application: 7 layers.",
    topic: "OSI Model",
  },
  {
    categorySlug: "net",
    type: "PICTURE",
    difficulty: "AVERAGE",
    questionText: "Name this network topology.",
    codeSnippet: null,
    imageUrl: "/static/images/ring.svg",
    answer: "Ring topology",
    alternates: ["ring"],
    choices: [],
    hint: "Data travels in a circle.",
    explanation: "In a ring topology each node connects to exactly two neighbors, forming a closed loop.",
    topic: "Topologies",
  },
  {
    categorySlug: "net",
    type: "MULTIPLE_CHOICE",
    difficulty: "AVERAGE",
    questionText: "What is the default port number of HTTPS?",
    codeSnippet: null,
    imageUrl: null,
    answer: "443",
    alternates: [],
    choices: ["80","21","8080"],
    hint: "HTTP is 80; the secure one is different.",
    explanation: "HTTPS uses TCP port 443. HTTP uses 80, and FTP uses 21.",
    topic: "Ports",
  },
  {
    categorySlug: "net",
    type: "MULTIPLE_CHOICE",
    difficulty: "AVERAGE",
    questionText: "Which protocol automatically assigns IP addresses to hosts?",
    codeSnippet: null,
    imageUrl: null,
    answer: "DHCP",
    alternates: [],
    choices: ["DNS","FTP","ARP"],
    hint: "D for Dynamic.",
    explanation: "Dynamic Host Configuration Protocol leases IP address, subnet mask, gateway, and DNS settings to clients.",
    topic: "Protocols",
  },
  {
    categorySlug: "net",
    type: "WORD_PUZZLE",
    difficulty: "AVERAGE",
    questionText: "The system that translates domain names like jhcsc.edu.ph into IP addresses (acronym).",
    codeSnippet: null,
    imageUrl: null,
    answer: "DNS",
    alternates: [],
    choices: [],
    hint: "The \"phonebook\" of the internet.",
    explanation: "The Domain Name System resolves human-friendly names to IP addresses.",
    topic: "Protocols",
  },
  {
    categorySlug: "net",
    type: "PICTURE",
    difficulty: "AVERAGE",
    questionText: "Name this network topology.",
    codeSnippet: null,
    imageUrl: "/static/images/mesh.svg",
    answer: "Mesh topology",
    alternates: ["mesh","full mesh"],
    choices: [],
    hint: "Every node links to every other node.",
    explanation: "A full mesh gives redundant paths: n nodes need n(n−1)/2 links. Here 5 nodes use 10 links.",
    topic: "Topologies",
  },
  {
    categorySlug: "net",
    type: "MULTIPLE_CHOICE",
    difficulty: "DIFFICULT",
    questionText: "How many USABLE host addresses are in a /26 subnet?",
    codeSnippet: null,
    imageUrl: null,
    answer: "62",
    alternates: [],
    choices: ["64","30","126"],
    hint: null,
    explanation: "/26 leaves 6 host bits: 2⁶ = 64 addresses, minus the network and broadcast addresses = 62.",
    topic: "Subnetting",
  },
  {
    categorySlug: "net",
    type: "MULTIPLE_CHOICE",
    difficulty: "DIFFICULT",
    questionText: "A standard switch forwards frames using MAC addresses. At which OSI layer does it operate?",
    codeSnippet: null,
    imageUrl: null,
    answer: "Data Link (Layer 2)",
    alternates: [],
    choices: ["Network (Layer 3)","Physical (Layer 1)","Transport (Layer 4)"],
    hint: null,
    explanation: "MAC addresses belong to the Data Link layer, so a standard switch is a Layer 2 device.",
    topic: "OSI Model",
  },
  {
    categorySlug: "net",
    type: "WORD_PUZZLE",
    difficulty: "DIFFICULT",
    questionText: "Connectionless transport protocol that does not guarantee delivery, used for video calls (acronym).",
    codeSnippet: null,
    imageUrl: null,
    answer: "UDP",
    alternates: [],
    choices: [],
    hint: null,
    explanation: "User Datagram Protocol trades reliability for speed. TCP is the connection-oriented, reliable one.",
    topic: "Protocols",
  },
  {
    categorySlug: "net",
    type: "MULTIPLE_CHOICE",
    difficulty: "DIFFICULT",
    questionText: "Which of these is a PRIVATE IPv4 address?",
    codeSnippet: null,
    imageUrl: null,
    answer: "172.16.5.4",
    alternates: [],
    choices: ["8.8.8.8","172.32.0.1","11.0.0.1"],
    hint: null,
    explanation: "Private ranges: 10.0.0.0/8, 172.16.0.0–172.31.255.255, and 192.168.0.0/16. 172.32.x.x is public.",
    topic: "Addressing",
  },
  {
    categorySlug: "net",
    type: "MULTIPLE_CHOICE",
    difficulty: "DIFFICULT",
    questionText: "What is the network address of host 192.168.10.77/27?",
    codeSnippet: null,
    imageUrl: null,
    answer: "192.168.10.64",
    alternates: [],
    choices: ["192.168.10.0","192.168.10.96","192.168.10.32"],
    hint: null,
    explanation: "/27 makes blocks of 32: 0, 32, 64, 96… Host .77 falls in the 64–95 block, so the network is .64.",
    topic: "Subnetting",
  },
  {
    categorySlug: "web",
    type: "MULTIPLE_CHOICE",
    difficulty: "EASY",
    questionText: "What does HTML stand for?",
    codeSnippet: null,
    imageUrl: null,
    answer: "HyperText Markup Language",
    alternates: [],
    choices: ["HighText Machine Language","HyperTool Multi Language","Home Tool Markup Language"],
    hint: "It \"marks up\" content.",
    explanation: "HTML is the markup language that structures the content of web pages.",
    topic: "HTML",
  },
  {
    categorySlug: "web",
    type: "PICTURE",
    difficulty: "EASY",
    questionText: "What HTML element is shown?",
    codeSnippet: null,
    imageUrl: "/static/images/html_anchor.svg",
    answer: "Anchor",
    alternates: ["a","anchor tag","link","hyperlink","a tag"],
    choices: [],
    hint: "Ships drop one; it \"links\" to another page.",
    explanation: "The <a> (anchor) element creates a hyperlink. The href attribute holds the destination.",
    topic: "HTML",
  },
  {
    categorySlug: "web",
    type: "WORD_PUZZLE",
    difficulty: "EASY",
    questionText: "Language used to style and lay out web pages (acronym).",
    codeSnippet: null,
    imageUrl: null,
    answer: "CSS",
    alternates: ["cascading style sheets"],
    choices: [],
    hint: "Cascading ___ ___.",
    explanation: "Cascading Style Sheets control colors, fonts, spacing, and layout.",
    topic: "CSS",
  },
  {
    categorySlug: "web",
    type: "MULTIPLE_CHOICE",
    difficulty: "EASY",
    questionText: "Which tag creates the LARGEST default heading?",
    codeSnippet: null,
    imageUrl: null,
    answer: "<h1>",
    alternates: [],
    choices: ["<h6>","<head>","<heading>"],
    hint: "Lower number = bigger.",
    explanation: "<h1> is the top-level heading. <h6> is the smallest. <head> holds page metadata, not a heading.",
    topic: "HTML",
  },
  {
    categorySlug: "web",
    type: "WORD_PUZZLE",
    difficulty: "EASY",
    questionText: "Application used to open and view websites, e.g., Chrome or Firefox.",
    codeSnippet: null,
    imageUrl: null,
    answer: "BROWSER",
    alternates: [],
    choices: [],
    hint: "You \"browse\" with it.",
    explanation: "A web browser requests pages from servers and renders the HTML, CSS, and JavaScript.",
    topic: "Fundamentals",
  },
  {
    categorySlug: "web",
    type: "PICTURE",
    difficulty: "AVERAGE",
    questionText: "Name the CSS concept illustrated.",
    codeSnippet: null,
    imageUrl: "/static/images/boxmodel.svg",
    answer: "Box model",
    alternates: ["css box model"],
    choices: [],
    hint: "Every element is a rectangle.",
    explanation: "The CSS box model: content, then padding, then border, then margin, from the inside out.",
    topic: "CSS",
  },
  {
    categorySlug: "web",
    type: "MULTIPLE_CHOICE",
    difficulty: "AVERAGE",
    questionText: "Which HTTP method is normally used to submit a form that CREATES a new record?",
    codeSnippet: null,
    imageUrl: null,
    answer: "POST",
    alternates: [],
    choices: ["GET","DELETE","HEAD"],
    hint: "Like posting a letter.",
    explanation: "POST sends data in the request body to create a resource. GET only retrieves.",
    topic: "HTTP",
  },
  {
    categorySlug: "web",
    type: "MULTIPLE_CHOICE",
    difficulty: "AVERAGE",
    questionText: "document.getElementById(\"score\") belongs to which API?",
    codeSnippet: null,
    imageUrl: null,
    answer: "DOM",
    alternates: [],
    choices: ["JSON","AJAX","HTTP"],
    hint: "It represents the page as a tree of nodes.",
    explanation: "The Document Object Model lets JavaScript read and change HTML elements.",
    topic: "JavaScript",
  },
  {
    categorySlug: "web",
    type: "WORD_PUZZLE",
    difficulty: "AVERAGE",
    questionText: "One-dimensional CSS layout model enabled by display: flex.",
    codeSnippet: null,
    imageUrl: null,
    answer: "FLEXBOX",
    alternates: [],
    choices: [],
    hint: "Flexible ___.",
    explanation: "Flexbox arranges items in a row or column and handles alignment and spacing.",
    topic: "CSS",
  },
  {
    categorySlug: "web",
    type: "MULTIPLE_CHOICE",
    difficulty: "AVERAGE",
    questionText: "Which HTTP status code means \"Not Found\"?",
    codeSnippet: null,
    imageUrl: null,
    answer: "404",
    alternates: [],
    choices: ["500","301","200"],
    hint: "The most famous error page.",
    explanation: "404 means the resource does not exist. 200 = OK, 301 = moved, and 500 = server error.",
    topic: "HTTP",
  },
  {
    categorySlug: "web",
    type: "MULTIPLE_CHOICE",
    difficulty: "DIFFICULT",
    questionText: "What does this print?",
    codeSnippet: "console.log(typeof null);",
    imageUrl: null,
    answer: "object",
    alternates: [],
    choices: ["null","undefined","number"],
    hint: null,
    explanation: "A long-standing JavaScript quirk: typeof null returns \"object\".",
    topic: "JavaScript",
  },
  {
    categorySlug: "web",
    type: "MULTIPLE_CHOICE",
    difficulty: "DIFFICULT",
    questionText: "What does this print?",
    codeSnippet: "console.log(0.1 + 0.2 === 0.3);",
    imageUrl: null,
    answer: "false",
    alternates: [],
    choices: ["true","undefined","NaN"],
    hint: null,
    explanation: "Floating-point rounding makes 0.1 + 0.2 equal 0.30000000000000004, so the comparison is false.",
    topic: "JavaScript",
  },
  {
    categorySlug: "web",
    type: "WORD_PUZZLE",
    difficulty: "DIFFICULT",
    questionText: "Browser mechanism that lets a server allow requests from other origins (acronym).",
    codeSnippet: null,
    imageUrl: null,
    answer: "CORS",
    alternates: [],
    choices: [],
    hint: null,
    explanation: "Cross-Origin Resource Sharing uses headers like Access-Control-Allow-Origin to relax the same-origin policy.",
    topic: "Security",
  },
  {
    categorySlug: "web",
    type: "MULTIPLE_CHOICE",
    difficulty: "DIFFICULT",
    questionText: "Which selector has the HIGHEST specificity?",
    codeSnippet: null,
    imageUrl: null,
    answer: "#menu",
    alternates: [],
    choices: [".menu a","div ul li","*"],
    hint: null,
    explanation: "An ID selector (1,0,0) beats classes (0,1,0) and elements (0,0,1). * has zero specificity.",
    topic: "CSS",
  },
  {
    categorySlug: "web",
    type: "PICTURE",
    difficulty: "DIFFICULT",
    questionText: "What value is logged?",
    codeSnippet: null,
    imageUrl: "/static/images/js_code.svg",
    answer: "4",
    alternates: ["four"],
    choices: [],
    hint: null,
    explanation: "b = a copies the reference, not the array. Pushing to b also changes a, so a.length is 4.",
    topic: "JavaScript",
  },
  {
    categorySlug: "sad",
    type: "MULTIPLE_CHOICE",
    difficulty: "EASY",
    questionText: "What does SDLC stand for?",
    codeSnippet: null,
    imageUrl: null,
    answer: "Systems Development Life Cycle",
    alternates: [],
    choices: ["Software Design Logic Code","System Data Link Control","Structured Development Language Cycle"],
    hint: "A \"cycle\" of building systems.",
    explanation: "The SDLC is the series of phases for planning, building, testing, deploying, and maintaining a system.",
    topic: "SDLC",
  },
  {
    categorySlug: "sad",
    type: "PICTURE",
    difficulty: "EASY",
    questionText: "In a use case diagram, what is this stick figure called?",
    codeSnippet: null,
    imageUrl: "/static/images/usecase_actor.svg",
    answer: "Actor",
    alternates: [],
    choices: [],
    hint: "Someone who \"acts\" on the system.",
    explanation: "An actor is a user or external system that interacts with the system, like Student or Administrator.",
    topic: "UML",
  },
  {
    categorySlug: "sad",
    type: "WORD_PUZZLE",
    difficulty: "EASY",
    questionText: "Professional who studies business problems and designs information system solutions.",
    codeSnippet: null,
    imageUrl: null,
    answer: "SYSTEMS ANALYST",
    alternates: ["system analyst"],
    choices: [],
    hint: "They \"analyze\" systems.",
    explanation: "A systems analyst bridges users and developers by gathering requirements and designing solutions.",
    topic: "Roles",
  },
  {
    categorySlug: "sad",
    type: "MULTIPLE_CHOICE",
    difficulty: "EASY",
    questionText: "In which phase do analysts gather what the users need?",
    codeSnippet: null,
    imageUrl: null,
    answer: "Requirements analysis",
    alternates: [],
    choices: ["Testing","Maintenance","Deployment"],
    hint: "Surveys and interviews happen here.",
    explanation: "Requirements analysis collects functional and non-functional requirements through surveys, interviews, and observation.",
    topic: "SDLC",
  },
  {
    categorySlug: "sad",
    type: "WORD_PUZZLE",
    difficulty: "EASY",
    questionText: "An early working model of a system shown to users for feedback.",
    codeSnippet: null,
    imageUrl: null,
    answer: "PROTOTYPE",
    alternates: [],
    choices: [],
    hint: "You are using one right now.",
    explanation: "A prototype lets users try the design early so problems are found before full development.",
    topic: "Methods",
  },
  {
    categorySlug: "sad",
    type: "PICTURE",
    difficulty: "AVERAGE",
    questionText: "Name this SDLC model.",
    codeSnippet: null,
    imageUrl: "/static/images/waterfall.svg",
    answer: "Waterfall",
    alternates: ["waterfall model"],
    choices: [],
    hint: "Phases flow downward like water.",
    explanation: "The Waterfall model finishes each phase before the next begins, with little room to go back.",
    topic: "SDLC",
  },
  {
    categorySlug: "sad",
    type: "PICTURE",
    difficulty: "AVERAGE",
    questionText: "In a DFD (Yourdon notation), what does the circle represent?",
    codeSnippet: null,
    imageUrl: "/static/images/dfd_process.svg",
    answer: "Process",
    alternates: ["a process","process symbol"],
    choices: [],
    hint: "It transforms input data into output.",
    explanation: "Circles are processes, rectangles are external entities, and open-ended boxes are data stores.",
    topic: "DFD",
  },
  {
    categorySlug: "sad",
    type: "MULTIPLE_CHOICE",
    difficulty: "AVERAGE",
    questionText: "Which feasibility study asks, \"Do the benefits justify the cost?\"",
    codeSnippet: null,
    imageUrl: null,
    answer: "Economic",
    alternates: [],
    choices: ["Technical","Operational","Schedule"],
    hint: "It is about money.",
    explanation: "Economic feasibility compares costs against expected benefits (cost-benefit analysis).",
    topic: "Feasibility",
  },
  {
    categorySlug: "sad",
    type: "WORD_PUZZLE",
    difficulty: "AVERAGE",
    questionText: "Agile framework that uses sprints, a Product Owner, and a ___ Master.",
    codeSnippet: null,
    imageUrl: null,
    answer: "SCRUM",
    alternates: [],
    choices: [],
    hint: "Named after a rugby formation.",
    explanation: "Scrum organizes work into short sprints with defined roles and ceremonies.",
    topic: "Methods",
  },
  {
    categorySlug: "sad",
    type: "MULTIPLE_CHOICE",
    difficulty: "AVERAGE",
    questionText: "Which UML diagram shows the ORDER of messages between objects over time?",
    codeSnippet: null,
    imageUrl: null,
    answer: "Sequence diagram",
    alternates: [],
    choices: ["Class diagram","Activity diagram","Use case diagram"],
    hint: "Messages happen in \"sequence\".",
    explanation: "A sequence diagram uses lifelines and arrows to show message order, e.g., App → API → Database.",
    topic: "UML",
  },
  {
    categorySlug: "sad",
    type: "MULTIPLE_CHOICE",
    difficulty: "DIFFICULT",
    questionText: "\"Use Hint\" happens only SOMETIMES during \"Answer Question\". Which use case relationship fits?",
    codeSnippet: null,
    imageUrl: null,
    answer: "«extend»",
    alternates: [],
    choices: ["«include»","Generalization","Aggregation"],
    hint: null,
    explanation: "«extend» is optional behavior added under a condition. «include» is behavior that always happens.",
    topic: "UML",
  },
  {
    categorySlug: "sad",
    type: "MULTIPLE_CHOICE",
    difficulty: "DIFFICULT",
    questionText: "Testing done by end users to confirm the system meets their needs before release.",
    codeSnippet: null,
    imageUrl: null,
    answer: "User acceptance testing",
    alternates: [],
    choices: ["Unit testing","Integration testing","Regression testing"],
    hint: null,
    explanation: "UAT is the final check by real users performing real tasks, as in Chapter III.",
    topic: "Testing",
  },
  {
    categorySlug: "sad",
    type: "WORD_PUZZLE",
    difficulty: "DIFFICULT",
    questionText: "Uncontrolled growth of a project's requirements after it has started.",
    codeSnippet: null,
    imageUrl: null,
    answer: "SCOPE CREEP",
    alternates: [],
    choices: [],
    hint: null,
    explanation: "Scope creep adds features without adjusting time or budget. A clear Scope and Limitation section prevents it.",
    topic: "Project Management",
  },
  {
    categorySlug: "sad",
    type: "MULTIPLE_CHOICE",
    difficulty: "DIFFICULT",
    questionText: "A Student \"is a\" User. In a class diagram this relationship is called ___.",
    codeSnippet: null,
    imageUrl: null,
    answer: "Generalization",
    alternates: [],
    choices: ["Aggregation","Composition","Dependency"],
    hint: null,
    explanation: "Generalization (inheritance) is drawn with a hollow triangle pointing to the parent class.",
    topic: "UML",
  },
  {
    categorySlug: "sad",
    type: "MULTIPLE_CHOICE",
    difficulty: "DIFFICULT",
    questionText: "One student plays many game sessions; each session belongs to one student. The cardinality is:",
    codeSnippet: null,
    imageUrl: null,
    answer: "One-to-many",
    alternates: [],
    choices: ["One-to-one","Many-to-many","Many-to-one from Student"],
    hint: null,
    explanation: "Student 1 — * GameSession: the foreign key user_id lives on the \"many\" side (game_sessions).",
    topic: "ERD",
  },
  {
    categorySlug: "ias",
    type: "MULTIPLE_CHOICE",
    difficulty: "EASY",
    questionText: "The CIA triad of information security stands for?",
    codeSnippet: null,
    imageUrl: null,
    answer: "Confidentiality, Integrity, Availability",
    alternates: [],
    choices: ["Control, Identity, Access","Cyber, Internet, Authentication","Confidentiality, Identity, Authorization"],
    hint: "Secrecy, accuracy, and uptime.",
    explanation: "Confidentiality keeps data secret, Integrity keeps it accurate, and Availability keeps it accessible.",
    topic: "CIA Triad",
  },
  {
    categorySlug: "ias",
    type: "PICTURE",
    difficulty: "EASY",
    questionText: "Name the security control shown between the Internet and the LAN.",
    codeSnippet: null,
    imageUrl: "/static/images/firewall.svg",
    answer: "Firewall",
    alternates: [],
    choices: [],
    hint: "A wall that stops \"fire\".",
    explanation: "A firewall filters traffic between networks based on rules, blocking unauthorized connections.",
    topic: "Network Security",
  },
  {
    categorySlug: "ias",
    type: "WORD_PUZZLE",
    difficulty: "EASY",
    questionText: "Malware that encrypts your files and demands payment to unlock them.",
    codeSnippet: null,
    imageUrl: null,
    answer: "RANSOMWARE",
    alternates: [],
    choices: [],
    hint: "Kidnappers ask for a \"ransom\".",
    explanation: "Ransomware holds data hostage. Offline backups are the best defense.",
    topic: "Malware",
  },
  {
    categorySlug: "ias",
    type: "MULTIPLE_CHOICE",
    difficulty: "EASY",
    questionText: "Which is the STRONGEST password?",
    codeSnippet: null,
    imageUrl: null,
    answer: "T#9vq!Lm2@Rz",
    alternates: [],
    choices: ["password123","juan1999","12345678"],
    hint: "Length plus a mix of character types.",
    explanation: "Strong passwords are long and mix upper and lower case, numbers, and symbols, with no personal info.",
    topic: "Passwords",
  },
  {
    categorySlug: "ias",
    type: "PICTURE",
    difficulty: "EASY",
    questionText: "This email is an example of what attack?",
    codeSnippet: null,
    imageUrl: "/static/images/phishing.svg",
    answer: "Phishing",
    alternates: ["phishing email","phishing attack"],
    choices: [],
    hint: "Sounds like \"fishing\" for passwords.",
    explanation: "Phishing uses fake, urgent messages to trick victims into revealing credentials.",
    topic: "Social Engineering",
  },
  {
    categorySlug: "ias",
    type: "MULTIPLE_CHOICE",
    difficulty: "AVERAGE",
    questionText: "Verifying WHO a user is (e.g., checking email and password).",
    codeSnippet: null,
    imageUrl: null,
    answer: "Authentication",
    alternates: [],
    choices: ["Authorization","Accounting","Auditing"],
    hint: "Proving you are authentic.",
    explanation: "Authentication confirms identity. Authorization decides what that identity may do.",
    topic: "Access Control",
  },
  {
    categorySlug: "ias",
    type: "PICTURE",
    difficulty: "AVERAGE",
    questionText: "Decode the ciphertext using the Caesar cipher (shift 3).",
    codeSnippet: null,
    imageUrl: "/static/images/caesar.svg",
    answer: "HELLO",
    alternates: [],
    choices: [],
    hint: "Shift each letter BACK by 3.",
    explanation: "K→H, H→E, O→L, O→L, R→O. KHOOR decodes to HELLO.",
    topic: "Cryptography",
  },
  {
    categorySlug: "ias",
    type: "WORD_PUZZLE",
    difficulty: "AVERAGE",
    questionText: "Login that requires two or more proofs of identity, like a password plus an OTP (acronym).",
    codeSnippet: null,
    imageUrl: null,
    answer: "MFA",
    alternates: ["2fa","multi factor authentication"],
    choices: [],
    hint: "Multi-___ Authentication.",
    explanation: "Multi-Factor Authentication combines something you know, have, or are.",
    topic: "Access Control",
  },
  {
    categorySlug: "ias",
    type: "MULTIPLE_CHOICE",
    difficulty: "AVERAGE",
    questionText: "Attack that floods a server with traffic from many machines to make it unavailable.",
    codeSnippet: null,
    imageUrl: null,
    answer: "DDoS",
    alternates: [],
    choices: ["Phishing","SQL injection","Spoofing"],
    hint: "It attacks Availability.",
    explanation: "Distributed Denial of Service uses many compromised devices (a botnet) to overwhelm a target.",
    topic: "Attacks",
  },
  {
    categorySlug: "ias",
    type: "MULTIPLE_CHOICE",
    difficulty: "AVERAGE",
    questionText: "Which scenario is a violation of INTEGRITY?",
    codeSnippet: null,
    imageUrl: null,
    answer: "An attacker changes a student's score in the database",
    alternates: [],
    choices: ["The server goes offline for an hour","Someone reads another user's private messages","A laptop with records is stolen"],
    hint: "Integrity = data is accurate and unaltered.",
    explanation: "Unauthorized modification breaks integrity. Reading data breaks confidentiality; downtime breaks availability.",
    topic: "CIA Triad",
  },
  {
    categorySlug: "ias",
    type: "MULTIPLE_CHOICE",
    difficulty: "DIFFICULT",
    questionText: "Typing this into a login form's username field is an attempt at?",
    codeSnippet: "' OR '1'='1",
    imageUrl: null,
    answer: "SQL injection",
    alternates: [],
    choices: ["Cross-site scripting","CSRF","Brute force"],
    hint: null,
    explanation: "It makes the WHERE clause always true. Parameterized queries (as Prisma uses) prevent it.",
    topic: "Attacks",
  },
  {
    categorySlug: "ias",
    type: "MULTIPLE_CHOICE",
    difficulty: "DIFFICULT",
    questionText: "Why store passwords with bcrypt instead of plain SHA-256?",
    codeSnippet: null,
    imageUrl: null,
    answer: "bcrypt is salted and deliberately slow, resisting brute force",
    alternates: [],
    choices: ["bcrypt can be decrypted if the user forgets","SHA-256 is not a hash function","bcrypt makes passwords shorter"],
    hint: null,
    explanation: "Fast hashes let attackers try billions of guesses per second. bcrypt's cost factor and salt slow that down.",
    topic: "Cryptography",
  },
  {
    categorySlug: "ias",
    type: "WORD_PUZZLE",
    difficulty: "DIFFICULT",
    questionText: "Asymmetric encryption uses a public key and a ___ key.",
    codeSnippet: null,
    imageUrl: null,
    answer: "PRIVATE",
    alternates: [],
    choices: [],
    hint: null,
    explanation: "Data encrypted with the public key can only be decrypted with the matching private key.",
    topic: "Cryptography",
  },
  {
    categorySlug: "ias",
    type: "MULTIPLE_CHOICE",
    difficulty: "DIFFICULT",
    questionText: "A faculty account can view reports, but a student account cannot. This is enforced by ___.",
    codeSnippet: null,
    imageUrl: null,
    answer: "Role-based authorization",
    alternates: [],
    choices: ["Authentication only","Encryption","Hashing"],
    hint: null,
    explanation: "Role-based access control (RBAC) grants permissions by role. NestJS guards check the role in the JWT.",
    topic: "Access Control",
  },
  {
    categorySlug: "ias",
    type: "MULTIPLE_CHOICE",
    difficulty: "DIFFICULT",
    questionText: "A <script> tag posted in a comment runs in other users' browsers. This attack is:",
    codeSnippet: null,
    imageUrl: null,
    answer: "Cross-site scripting (XSS)",
    alternates: [],
    choices: ["SQL injection","Man-in-the-middle","DDoS"],
    hint: null,
    explanation: "XSS injects scripts into pages other users view. Escaping output prevents it.",
    topic: "Attacks",
  },
];
